### ISSUE TITLE
Make mixin 4 mandatory

### ISSUE THREAD

**Issue by sehiotbe** [alloyproject/alloy#4]
As recommended in [MRL-0004](https://lab.getmonero.org/pubs/MRL-0004.pdf) with preference for [recent outputs](https://github.com/monero-project/monero/pull/1996). There are privacy concerns with [0-mixin transactions](http://monerolink.com/monerolink.pdf).

**Comment by nighthawk18** [comment]
Thanks, we do plan to implement this as part of the next upgrade cycle. This does have a fee impact so we had to take that into account.
